<?php
/**
 * This file is part of the Receiptful extension.
 *
 * (c) Receiptful <info@receiptful.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Stefano Sala <stefano@receiptful.com>
 */
?>
<script src="<?php echo Receiptful_Core_ApiClient::getBaseUrl() . "/scripts/tracking.js"; ?>"></script>
<script type="text/javascript">Receiptful.setTrackingCookie();</script>
